### ISSUE TITLE
Install error on Win 10

### ISSUE THREAD

**Issue by snortman-kcl** [cypresssemiconductorco/modustoolbox-software#1]
Running the latest version of Win10  10.0.19041 Build 19041

Downloaded latest version of ModusToolbox from the Cypress page:
ModusToolbox_2.3.0.4267-windows-install.exe

After downloading, I go to the install file location and R-click and select "Run as administrator"

I select the default of "install for me only" and I receive an error message:

Some components that are required for ModusToolbox to run properly were not installed. Please launch the installation again with administrative privileges, or enter the administrative credentials during the installation and ensure two missing components are selected:

-ModusToolbox Drivers
-ModusToolbox Prerequisites

![image](https://user-images.githubusercontent.com/83666661/119020779-a6254900-b96c-11eb-9cee-a52ac5a7b803.png)

I've uninstalled/reinstalled numerous times, ensuring that I am running as an admin, and I get the same error every time.  Please advise.

**Comment by ddka22** [comment]
Hello @snortman-kcl,

During installation, you will find the option to select the installation type. Change it to **Advanced Installation** and then select all the components as shown below. 
![image](https://user-images.githubusercontent.com/57934845/119098006-0252a080-ba33-11eb-984a-bfec5a5d666f.png)

After this change let me know if the installation proceeds successfully.

Regards,
Dheeraj

**Comment by snortman-kcl** [comment]
That worked, thank you
